// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gacxnkgazwybqyymfqpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhY3hua2dhend5YnF5eW1mcXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDE5MDUsImV4cCI6MjA2NTY3NzkwNX0.maSsPrq_8aPBw-SPXOar1qumrKgF-yjVbslNDqI8xaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);